module.exports = {
    MESSAGE_HEADER: 'FFAA',
    RESPONSE_CODE_ACK: '1C',

    RESPONSE_CODE_STAT_HEADER: '80',
    RESPONSE_CODE_STAT_FOOTER: '81',
    RESPONSE_CODE_STAT_VOLUME: '10',
    RESPONSE_CODE_STAT_OCCUPANCY: '11',
    RESPONSE_CODE_STAT_SPEED: '12',
    RESPONSE_CODE_STAT_GAP: '13',
    RESPONSE_CODE_STAT_C1: '14',
    RESPONSE_CODE_STAT_C2: '15',
    RESPONSE_CODE_STAT_C3: '16',
    RESPONSE_CODE_STAT_C4: '17',
    RESPONSE_CODE_STAT_C5: '18',
    RESPONSE_CODE_STAT_HEADWAY: '1E',
    RESPONSE_CODE_STAT_SPEED85: '1F',
    RESPONSE_CODE_STAT_HEADER: '80',

    ERROR_MESSAGE_HEADER_FRAME_NOT_AS_EXPECTED: 'Заголовок пакета отличается от ожидаемого'
}